name: "Help & Support"
description: "Please search existing issues and discussions before opening a new one."
body:
  - type: markdown
    attributes:
      value: |
        - **Documentation:** Check our [Quick Start](https://github.com/akashskypatel/ffmpeg-kit-extended/blob/main/flutter/docs/quick-start.md) guide.
        - **Search:** Use the GitHub search bar to see if your question has already been answered.
        - **Discussions:** Use [GitHub Discussions](https://github.com/akashskypatel/ffmpeg-kit-extended/discussions) for general questions.
