name: ffmpeg_kit_extended_flutter
description: FFmpeg Kit Extended for Flutter. Supports Windows and Linux.
repository: https://github.com/akashskypatel/ffmpeg-kit-extended
issue_tracker: https://github.com/akashskypatel/ffmpeg-kit-extended/issues
homepage: https://github.com/akashskypatel/ffmpeg-kit-extended
version: 0.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.2.0"

executables:
  configure: configure

flutter:
  plugin:
    platforms:
      android:
        package: com.akashskypatel.ffmpegkitextended.flutter
        pluginClass: FfmpegKitExtendedFlutterPlugin
      ios:
        pluginClass: FfmpegKitExtendedFlutterPlugin
      macos:
        pluginClass: FfmpegKitExtendedFlutterPlugin
      linux:
        pluginClass: FfmpegKitExtendedFlutterPlugin
      windows:
        pluginClass: FfmpegKitExtendedFlutterPlugin

dependencies:
  ffi: ^2.2.0
  flutter:
    sdk: flutter
  path: ^1.9.1
  path_provider: ^2.1.5
  yaml: ^3.1.2
dev_dependencies:
  ffigen: ^20.1.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  leak_tracker_flutter_testing: ^3.0.10
  plugin_platform_interface: ^2.1.5
  test: ^1.26.3

# ffmpeg_kit_extended_config:
#   version: "1.0.0"
#   type: "base"
#   gpl: true
#   small: true
#   windows: "\\\\wsl.localhost\\ManyLinux\\home\\vscode\\ffmpeg-kit-builders\\prebuilt\\windows-x86_64\\releases\\bundle-base-windows-x86_64-shared-debug-gpl.zip"
#   linux: "/home/vscode/ffmpeg-kit-builders/prebuilt/linux-x86_64/releases/bundle-base-linux-x86_64-shared-debug-gpl.zip"
